upgrade_pip: &upgrade_pip
  run:
    name: Upgrade pip
    command: pip install --upgrade pip wheel

install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: pip install . --upgrade && pip install ".[test]"

version: 2
jobs:
  test:
    working_directory: ~/openfisca-brestmetropole
    docker:
      - image: python:3.7
    steps:
      - checkout
      - *upgrade_pip
      - *install_dependencies
      - run:
          name: Run unit tests
          command: make test

workflows:
  version: 2
  test:
    jobs:
      - test
